# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-17 20:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('haas', '0002_add_triggers'),
    ]

    operations = [
        migrations.RunSQL(
            """
            CREATE OR REPLACE VIEW v_dr_pairs AS
            SELECT DISTINCT ON (herd_id)
                   r.herd_id, r.instance_id, r.master_id, r.server_id,
                   round(abs(coalesce(p.xlog_pos, 0) - 
                         coalesce(r.xlog_pos, 0)) / 1024.0, 1) AS mb_lag,
                   h.vhost
              FROM ele_instance r
              JOIN ele_instance p ON (p.instance_id = r.master_id)
              JOIN ele_herd h ON (h.herd_id = r.herd_id)
             WHERE r.is_online
               AND r.master_id IS NOT NULL
             ORDER BY herd_id, mb_lag DESC, r.instance_id;
            """
            """
            CREATE OR REPLACE VIEW v_flat_instance AS
            SELECT i.instance_id, i.version, h.pgdata, i.local_pgdata,
                   i.xlog_pos, i.is_online, h.base_name, h.herd_name,
                   h.db_port, h.vhost, s.server_id, s.hostname, i.master_id,
                   e.environment_id, e.env_name
              FROM ele_instance i
              JOIN ele_herd h USING (herd_id)
              JOIN ele_environment e USING (environment_id)
              JOIN ele_server s USING (server_id);
            """
        )
    ]
