# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-18 21:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haas', '0003_add_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herd',
            name='base_name',
            field=models.CharField(help_text=b'Used to identify this herd, and for CLI tools called within the underlying OS.', max_length=40, verbose_name=b'Instance'),
        ),
    ]
