# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-13 12:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('haas', '0004_auto_20160818_1626'),
    ]

    operations = [
        migrations.RunSQL(
            """
            CREATE OR REPLACE VIEW v_dr_pairs AS
            SELECT DISTINCT ON (herd_id)
                   r.herd_id, r.instance_id, r.master_id, r.server_id,
                   round(abs(coalesce(p.xlog_pos, 0) - 
                     coalesce(r.xlog_pos, 0)) / 1024.0 / 1024.0, 1) AS mb_lag,
                   h.vhost
              FROM ele_instance r
              JOIN ele_instance p ON (p.instance_id = r.master_id)
              JOIN ele_herd h ON (h.herd_id = r.herd_id)
             WHERE r.is_online
               AND r.master_id IS NOT NULL
             ORDER BY herd_id, mb_lag, r.instance_id;
            """
        )
    ]
